# sigit/services/user_recon.py
from typing import List, Dict

from ..core.client import AsyncClient
from ..core.colors import Colors

import asyncio

c = Colors()

class UserRecon:
    
    PLATFORMS = [
        "https://facebook.com/{username}",
        "https://instagram.com/{username}",
        "https://twitter.com/{username}",
        "https://youtube.com/@{username}",
        "https://tiktok.com/@{username}",
        "https://linkedin.com/in/{username}",
        "https://reddit.com/user/{username}",
        "https://pinterest.com/{username}",
        "https://tumblr.com/blog/{username}",
        "https://t.me/{username}",
        "https://vk.com/{username}",
        "https://github.com/{username}",
        "https://medium.com/@{username}",
        "https://dev.to/{username}",
        "https://behance.net/{username}",
        "https://dribbble.com/{username}",
        "https://keybase.io/{username}",
        "https://stackoverflow.com/users/{username}",
        "https://twitch.tv/{username}",
        "https://steamcommunity.com/id/{username}",
        "https://bilibili.com/{username}",
        "https://soundcloud.com/{username}",
        "https://bandcamp.com/{username}",
        "https://spotify.com/user/{username}",
        "https://patreon.com/{username}",
        "https://ko-fi.com/{username}",
        "https://saweria.co/{username}",
        "https://trakteer.id/{username}",
        "https://shopee.co.id/{username}",
        "https://www.tokopedia.com/{username}",
        "https://blibli.com/seller/{username}",
        "https://etsy.com/shop/{username}",
        "https://kaskus.co.id/profile/{username}",
        "https://forum.xda-developers.com/m/{username}",
        "https://vimeo.com/{username}",
        "https://flickr.com/people/{username}",
        "https://about.me/{username}",
        "https://last.fm/user/{username}",
        "https://roblox.com/user/{username}",
        "https://cash.app/$ {username}",
        "https://venmo.com/{username}",
        "https://paypal.me/{username}",
        "https://flipboard.com/@{username}",
        "https://ask.fm/{username}",
        "https://goodreads.com/{username}",
        "https://letterboxd.com/{username}",
        "https://myspace.com/{username}",
        "https://hackernews.com/user?id={username}",
        "https://repl.it/@{username}",
        "https://gitlab.com/{username}",
        "https://bitbucket.org/{username}",
        "https://npm.js.org/~{username}",
        "https://pypi.org/user/{username}",
        "https://dockerhub.com/u/{username}",
        "https://rubygems.org/profiles/{username}",
        "https://wordpress.com/members/@{username}",
        "https://ghost.org/{username}",
        "https://producthunt.com/@{username}",
        "https://quora.com/profile/{username}",
        "https://medium.com/u/{username}",
        "https://deviantart.com/{username}",
        "https://foursquare.com/user/{username}",
        "https://tripadvisor.com/Profile/{username}",
        "https://cnet.com/profiles/{username}",
        "https://forbes.com/profile/{username}",
        "https://wired.com/author/{username}",
        "https://vice.com/id/contributor/{username}",
        "https://line.me/ti/p/~{username}",
        "https://ello.co/{username}",
        "https://500px.com/p/{username}",
        "https://imgur.com/user/{username}",
        "https://gist.github.com/{username}",
        "https://speakerdeck.com/{username}",
        "https://slideshare.net/{username}",
        "https://scribd.com/user/{username}",
        "https://issuu.com/{username}",
        "https://zillow.com/profile/{username}",
        "https://realtor.com/realestateagents/{username}",
        "https://booking.com/profile/{username}",
        "https://airbnb.com/users/show/{username}",
        "https://detik.com/{username}",
        "https://kompas.com/profile/{username}",
        "https://suara.com/profile/{username}",
        "https://idntimes.com/profile/{username}",
        "https://liputan6.com/tag/{username}",
        "https://discord.com/users/{username}",
        "https://xboxgamertag.com/profile/{username}",
        "https://psnprofiles.com/{username}",
        "https://epicgames.com/store/id/{username}",
        "https://dailymotion.com/{username}",
        "https://imdb.com/user/{username}",
        "https://deezer.com/profile/{username}",
        "https://ebay.com/usr/{username}",
        "https://amazon.com/gp/profile/{username}",
        "https://myanimelist.net/profile/{username}",
        "https://gettr.com/user/{username}",
        "https://gab.com/{username}",
        "https://truthsocial.com/@{username}",
        "https://minds.com/{username}",
        "https://rumble.com/user/{username}",
        "https://odysee.com/@{username}:{username}",
        "https://mastodon.social/@{username}",
        "https://nextdoor.com/profile/{username}",
        "https://snapchat.com/add/{username}",
        "https://weibo.com/u/{username}",
        "https://zcool.com.cn/u/{username}",
        "https://pixiv.net/users/{username}",
        "https://artstation.com/{username}",
        "https://smule.com/{username}",
        "https://anghami.com/user/{username}",
        "https://reverbnation.com/{username}",
        "https://fandom.com/user/{username}",
        "https://genius.com/{username}",
        "https://wattpad.com/user/{username}",
        "https://archiveofourown.org/users/{username}",
        "https://fanfiction.net/u/{username}",
        "https://indiegogo.com/individuals/{username}",
        "https://kickstarter.com/profile/{username}",
        "https://tokocrypto.com/user/{username}",
        "https://indodax.com/profile/{username}",
        "https://binance.com/en/profile/{username}",
        "https://kucoin.com/user/{username}",
        "https://okx.com/user/{username}",
        "https://www.webnovel.com/user/{username}",
        "https://www.novelupdates.com/user/{username}",
        "https://www.viva.co.id/tag/{username}",
        "https://www.merdeka.com/tag/{username}",
        "https://www.cnnindonesia.com/tag/{username}",
        "https://www.tirto.id/author/{username}",
        "https://neocities.org/site/{username}",
        "https://hashnode.com/@{username}",
        "https://ko-fi.com/i/{username}",
        "https://chess.com/member/{username}",
        "https://lichess.org/@/{username}",
        "https://medium.com/tag/{username}",
        "https://webtoon.com/user/{username}",
        "https://ko-fi.com/i/{username}",
        "https://tabelog.com/rvwr/{username}",
        "https://untappd.com/user/{username}",
        "https://rateyourmusic.com/user/{username}",
        "https://discogs.com/user/{username}",
        "https://carrd.co/{username}",
        "https://linktr.ee/{username}",
        "https://bio.link/{username}",
        "https://allmylinks.com/{username}",
        "https://withkoji.com/{username}",
        "https://beacons.ai/{username}",
        "https://notion.site/{username}",
        "https://miro.com/app/profile/{username}",
        "https://trello.com/{username}",
        "https://asana.com/app/profile/{username}",
        "https://slack.com/team/{username}",
        "https://zoom.us/profile/{username}",
        "https://meetup.com/members/{username}",
        "https://eventbrite.com/o/{username}",
        "https://ticketmaster.com/artist/{username}",
        "https://sehatq.com/profile/{username}",
        "https://halodoc.com/tanya-dokter/profile/{username}",
        "https://alodokter.com/komunitas/profile/{username}",
        "https://bukalapak.com/u/{username}",
        "https://id.carousell.com/u/{username}",
        "https://olx.co.id/profile/{username}",
        "https://traveloka.com/profile/{username}",
        "https://agoda.com/profile/{username}",
        "https://tiket.com/profil/{username}",
        "https://pegipegi.com/profile/{username}",
        "https://gotransit.com/profile/{username}",
        "https://grab.com/id/user/{username}",
        "https://gojek.com/id/user/{username}",
        "https://flip.id/profile/{username}",
        "https://dana.id/profile/{username}",
        "https://ovo.id/profile/{username}",
        "https://gopay.co.id/profile/{username}",
    ]

    @staticmethod
    async def check_username(username: str) -> List[Dict[str, str]]:
        results = []
        async with AsyncClient() as client:
            tasks = [UserRecon._check_platform(client, url.format(username=username)) for url in UserRecon.PLATFORMS]
            for coro in asyncio.as_completed(tasks):
                result = await coro
                if result:
                    results.append(result)
        return results

    @staticmethod
    async def _check_platform(client: AsyncClient, url: str) -> Dict | None:
        status, _ = await client.get(url)
        if status == 200:
            return {"url": url, "status": status, "color": c.GREEN}
        elif status == 404:
            return {"url": url, "status": status, "color": c.RED}
        elif status > 0:
            return {"url": url, "status": status, "color": c.YELLOW}
        return None