from sigit.services.social.user_recon.custom_checkers import (
    check_facebook_user,
    check_linkedin_user,
    check_snapchat_user,
    check_tinder_user,
    check_x_user,
)
from sigit.services.social.user_recon.models import PlatformRule

PLATFORMS: list[PlatformRule] = [
    PlatformRule(
        name="GitHub",
        category="Dev",
        url_template="https://github.com/{username}",
        check_url_template="https://api.github.com/users/{username}",
        is_json=True,
        json_verify_key="id",
        min_length=1,
        max_length=39,
        regex_pattern=r"^[a-zA-Z0-9](?:[a-zA-Z0-9]|-(?=[a-zA-Z0-9])){0,38}$",
    ),
    PlatformRule(
        name="GitLab",
        category="Dev",
        url_template="https://gitlab.com/{username}",
        check_url_template="https://gitlab.com/api/v4/users?username={username}",
        is_json=True,
        json_list_not_empty=True,
        min_length=1,
        max_length=255,
    ),
    PlatformRule(
        name="Docker Hub",
        category="Dev",
        url_template="https://hub.docker.com/u/{username}",
        check_url_template="https://hub.docker.com/v2/users/{username}/",
        is_json=True,
        json_verify_key="id",
        min_length=4,
        max_length=30,
        regex_pattern=r"^[a-zA-Z0-9]+(?:[._-][a-zA-Z0-9]+)*$",
    ),
    PlatformRule(
        name="Codeberg",
        category="Dev",
        url_template="https://codeberg.org/{username}",
        check_url_template="https://codeberg.org/api/v1/users/{username}",
        is_json=True,
        json_verify_key="id",
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="NPM",
        category="Dev",
        url_template="https://www.npmjs.com/~{username}",
        check_url_template="https://www.npmjs.com/~{username}",
        headers={"x-spiferack": "1"},
        is_json=True,
        json_verify_key="scope",
        negative_markers=("Scope not found",),
        min_length=1,
        max_length=214,
        regex_pattern=r"^[a-z0-9][a-z0-9_.-]*$",
    ),
    PlatformRule(
        name="PyPI",
        category="Dev",
        url_template="https://pypi.org/user/{username}/",
        check_url_template="https://pypi.org/user/{username}/",
        positive_markers=('<div class="profile-header', '<h1 class="profile-header__title'),
        negative_markers=("User not found", "404 Not Found"),
        min_length=1,
        max_length=50,
        regex_pattern=r"^[A-Za-z0-9._-]+$",
    ),
    PlatformRule(
        name="Dev.to",
        category="Dev",
        url_template="https://dev.to/{username}",
        check_url_template="https://dev.to/api/users/by_username?url={username}",
        is_json=True,
        json_verify_key="name",
        min_length=1,
        max_length=30,
    ),
    PlatformRule(
        name="Bitbucket",
        category="Dev",
        url_template="https://bitbucket.org/{username}/",
        check_url_template="https://bitbucket.org/{username}/",
        taken_status_codes=(200, 302),
        negative_markers=("Page Not Found", "Resource not found"),
        min_length=1,
        max_length=30,
        regex_pattern=r"^[a-z0-9][a-z0-9_-]*$",
    ),
    PlatformRule(
        name="CodePen",
        category="Dev",
        url_template="https://codepen.io/{username}",
        check_url_template="https://codepen.io/{username}",
        positive_markers=('id="profile-header"', "profile-name"),
        negative_markers=("404 Not Found", "Couldn't find that"),
        min_length=1,
        max_length=30,
    ),
    PlatformRule(
        name="Replit",
        category="Dev",
        url_template="https://replit.com/@{username}",
        check_url_template="https://replit.com/@{username}",
        positive_markers=('<script id="__NEXT_DATA__"',),
        negative_markers=("Page Not Found", "User not found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Kaggle",
        category="Dev",
        url_template="https://www.kaggle.com/{username}",
        check_url_template="https://www.kaggle.com/{username}",
        positive_markers=("<title>",),
        negative_markers=("Page Not Found", "404 Not Found"),
        min_length=1,
        max_length=32,
    ),
    PlatformRule(
        name="HackerNews",
        category="Dev",
        url_template="https://news.ycombinator.com/user?id={username}",
        check_url_template="https://news.ycombinator.com/user?id={username}",
        positive_markers=("created:", "karma:"),
        negative_markers=("No such user.",),
        min_length=2,
        max_length=15,
        regex_pattern=r"^[a-zA-Z0-9_-]+$",
    ),
    PlatformRule(
        name="Crates.io",
        category="Dev",
        url_template="https://crates.io/users/{username}",
        check_url_template="https://crates.io/api/v1/users/{username}",
        is_json=True,
        json_verify_key="user",
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Packagist",
        category="Dev",
        url_template="https://packagist.org/packages/{username}/",
        check_url_template="https://packagist.org/packages/{username}/",
        positive_markers=('class="package"', 'class="packages"'),
        negative_markers=("404 Not Found", "Page Not Found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="RubyGems",
        category="Dev",
        url_template="https://rubygems.org/profiles/{username}",
        check_url_template="https://rubygems.org/profiles/{username}",
        positive_markers=('class="profile__title"',),
        negative_markers=("Page not found", "404 Not Found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Asciinema",
        category="Dev",
        url_template="https://asciinema.org/~{username}",
        check_url_template="https://asciinema.org/~{username}",
        positive_markers=('class="user-profile"', 'class="username"'),
        negative_markers=("404 Not Found", "Not Found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="SourceForge",
        category="Dev",
        url_template="https://sourceforge.net/u/{username}/profile/",
        check_url_template="https://sourceforge.net/u/{username}/profile/",
        positive_markers=('id="user-profile"', 'class="profile-name"'),
        negative_markers=("User not found",),
        min_length=1,
        max_length=30,
    ),
    PlatformRule(
        name="HackerRank",
        category="Dev",
        url_template="https://www.hackerrank.com/profile/{username}",
        check_url_template="https://www.hackerrank.com/rest/hackers/{username}",
        is_json=True,
        json_verify_key="model",
        min_length=2,
        max_length=30,
    ),
    PlatformRule(
        name="TryHackMe",
        category="Dev",
        url_template="https://tryhackme.com/p/{username}",
        check_url_template="https://tryhackme.com/api/v2/public-profile?username={username}",
        is_json=True,
        json_verify_key="success",
        min_length=3,
        max_length=30,
    ),
    PlatformRule(
        name="Bugcrowd",
        category="Dev",
        url_template="https://bugcrowd.com/{username}",
        check_url_template="https://bugcrowd.com/{username}",
        positive_markers=('class="profile-header"', "data-bio"),
        negative_markers=("404 Not Found", "We couldn't find that page"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Telegram",
        category="Social",
        url_template="https://t.me/{username}",
        check_url_template="https://t.me/{username}",
        positive_markers=('<div class="tgme_page_extra">', '<div class="tgme_page_title">'),
        negative_markers=('<div class="tgme_page_icon">',),
        min_length=5,
        max_length=32,
        regex_pattern=r"^[a-zA-Z0-9_]{5,32}$",
    ),
    PlatformRule(
        name="Facebook",
        category="Social",
        url_template="https://www.facebook.com/{username}",
        custom_checker=check_facebook_user,
        min_length=1,
        max_length=50,
        regex_pattern=r"^[a-zA-Z0-9.]+$",
    ),
    PlatformRule(
        name="X",
        category="Social",
        url_template="https://x.com/{username}",
        custom_checker=check_x_user,
        min_length=1,
        max_length=15,
        regex_pattern=r"^[a-zA-Z0-9_]{1,15}$",
    ),
    PlatformRule(
        name="Snapchat",
        category="Social",
        url_template="https://www.snapchat.com/@{username}",
        custom_checker=check_snapchat_user,
        min_length=1,
        max_length=30,
    ),
    PlatformRule(
        name="LinkedIn",
        category="Social",
        url_template="https://www.linkedin.com/in/{username}",
        custom_checker=check_linkedin_user,
        min_length=3,
        max_length=100,
    ),
    PlatformRule(
        name="Instagram",
        category="Social",
        url_template="https://www.instagram.com/{username}/",
        positive_markers=('property="og:title"',),
        negative_markers=(
            "Sorry, this page isn't available.",
            "The link you followed may be broken",
        ),
        min_length=1,
        max_length=30,
        regex_pattern=r"^[a-zA-Z0-9._]{1,30}$",
    ),
    PlatformRule(
        name="Reddit",
        category="Social",
        url_template="https://www.reddit.com/user/{username}/",
        check_url_template="https://www.reddit.com/user/{username}/",
        negative_markers=(
            "nobody on Reddit goes by that name",
            "Sorry, nobody on Reddit",
            '"error": 404',
        ),
        min_length=3,
        max_length=20,
        regex_pattern=r"^[a-zA-Z0-9_-]{3,20}$",
    ),
    PlatformRule(
        name="Pinterest",
        category="Social",
        url_template="https://www.pinterest.com/{username}/",
        check_url_template="https://www.pinterest.com/{username}/",
        negative_markers=("User not found.", "ResourceNotFound"),
        min_length=3,
        max_length=30,
        regex_pattern=r"^[a-zA-Z0-9_]{3,30}$",
    ),
    PlatformRule(
        name="TikTok",
        category="Social",
        url_template="https://www.tiktok.com/@{username}",
        check_url_template="https://www.tiktok.com/embed/@{username}",
        headers={
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            ),
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
        },
        positive_markers=('"uniqueId"', '"userInfo"'),
        negative_markers=('"statusCode":10202',),
        min_length=2,
        max_length=24,
        regex_pattern=r"^[a-zA-Z0-9_.]+$",
    ),
    PlatformRule(
        name="YouTube",
        category="Social",
        url_template="https://www.youtube.com/@{username}",
        check_url_template="https://www.youtube.com/@{username}?cbrd=1&ucbcb=1",
        positive_markers=("var ytInitialData =",),
        negative_markers=("This channel does not exist", "404 Not Found"),
        min_length=3,
        max_length=30,
    ),
    PlatformRule(
        name="Mastodon",
        category="Social",
        url_template="https://mastodon.social/@{username}",
        check_url_template="https://mastodon.social/api/v1/accounts/lookup?acct={username}",
        is_json=True,
        json_verify_key="id",
        min_length=3,
        max_length=30,
        regex_pattern=r"^[a-zA-Z0-9_]+$",
    ),
    PlatformRule(
        name="Keybase",
        category="Social",
        url_template="https://keybase.io/{username}",
        check_url_template="https://keybase.io/_/api/1.0/user/lookup.json?usernames={username}",
        is_json=True,
        json_verify_key="them",
        min_length=2,
        max_length=16,
        regex_pattern=r"^[a-zA-Z0-9_]{2,16}$",
    ),
    PlatformRule(
        name="Linktree",
        category="Social",
        url_template="https://linktr.ee/{username}",
        check_url_template="https://linktr.ee/{username}",
        positive_markers=('id="__NEXT_DATA__"',),
        negative_markers=("Linktree | Page Not Found", "Page Not Found"),
        min_length=1,
        max_length=30,
    ),
    PlatformRule(
        name="Medium",
        category="Social",
        url_template="https://medium.com/@{username}",
        check_url_template="https://medium.com/@{username}",
        positive_markers=('name="author"', 'property="og:title"'),
        negative_markers=(">PAGE NOT FOUND<", "Out of nothing, something.", "404: Page not found"),
        min_length=1,
        max_length=30,
    ),
    PlatformRule(
        name="Disqus",
        category="Social",
        url_template="https://disqus.com/by/{username}/",
        check_url_template="https://disqus.com/by/{username}/",
        positive_markers=('class="user-profile"', "data-username="),
        negative_markers=("Page Not Found",),
        min_length=1,
        max_length=30,
    ),
    PlatformRule(
        name="About.me",
        category="Social",
        url_template="https://about.me/{username}",
        check_url_template="https://about.me/{username}",
        positive_markers=('class="user-profile"', 'property="og:title"'),
        negative_markers=("Page Not Found",),
        min_length=1,
        max_length=30,
    ),
    PlatformRule(
        name="Threads",
        category="Social",
        url_template="https://www.threads.net/@{username}",
        check_url_template="https://www.threads.net/@{username}",
        positive_markers=('property="og:title"',),
        negative_markers=("Page Not Found", "Sorry, this page isn't available"),
        min_length=1,
        max_length=30,
    ),
    PlatformRule(
        name="Bluesky",
        category="Social",
        url_template="https://bsky.app/profile/{username}.bsky.social",
        check_url_template="https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile?actor={username}.bsky.social",
        is_json=True,
        json_verify_key="did",
        min_length=3,
        max_length=30,
    ),
    PlatformRule(
        name="Substack",
        category="Social",
        url_template="https://{username}.substack.com",
        check_url_template="https://{username}.substack.com",
        positive_markers=('class="publication-header"', 'property="og:title"'),
        negative_markers=("Page not found", "404 Not Found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Steam",
        category="Gaming",
        url_template="https://steamcommunity.com/id/{username}/",
        check_url_template="https://steamcommunity.com/id/{username}/",
        positive_markers=('"steamid"',),
        negative_markers=("Error</title>", "The specified profile could not be found."),
        min_length=2,
        max_length=32,
    ),
    PlatformRule(
        name="Chess.com",
        category="Gaming",
        url_template="https://www.chess.com/member/{username}",
        check_url_template="https://api.chess.com/pub/player/{username}",
        is_json=True,
        json_verify_key="player_id",
        min_length=3,
        max_length=30,
    ),
    PlatformRule(
        name="Lichess",
        category="Gaming",
        url_template="https://lichess.org/@/{username}",
        check_url_template="https://lichess.org/api/user/{username}",
        is_json=True,
        json_verify_key="id",
        min_length=2,
        max_length=30,
    ),
    PlatformRule(
        name="Speedrun.com",
        category="Gaming",
        url_template="https://www.speedrun.com/user/{username}",
        check_url_template="https://www.speedrun.com/api/v1/users/{username}",
        is_json=True,
        json_verify_key="data",
        min_length=1,
        max_length=30,
    ),
    PlatformRule(
        name="Roblox",
        category="Gaming",
        url_template="https://www.roblox.com/user.aspx?username={username}",
        check_url_template="https://www.roblox.com/user.aspx?username={username}",
        positive_markers=('class="profile-header"', "profile-avatar"),
        negative_markers=("Page cannot be found",),
        min_length=3,
        max_length=20,
    ),
    PlatformRule(
        name="Itch.io",
        category="Gaming",
        url_template="https://{username}.itch.io",
        check_url_template="https://{username}.itch.io",
        positive_markers=('class="user_page"', 'class="user_profile"'),
        negative_markers=("Not Found",),
        min_length=3,
        max_length=30,
    ),
    PlatformRule(
        name="SoundCloud",
        category="Music",
        url_template="https://soundcloud.com/{username}",
        check_url_template="https://soundcloud.com/{username}",
        positive_markers=("soundcloud://users:", '"username":"'),
        negative_markers=("We can't find that user", "404 Not Found"),
        min_length=3,
        max_length=32,
    ),
    PlatformRule(
        name="Spotify",
        category="Music",
        url_template="https://open.spotify.com/user/{username}",
        check_url_template="https://api.stats.fm/api/v1/users/{username}",
        is_json=True,
        json_verify_key="item",
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Mixcloud",
        category="Music",
        url_template="https://www.mixcloud.com/{username}/",
        check_url_template="https://www.mixcloud.com/{username}/",
        positive_markers=('class="profile-header"', 'class="user-name"'),
        negative_markers=("Page Not Found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Last.fm",
        category="Music",
        url_template="https://www.last.fm/user/{username}",
        check_url_template="https://www.last.fm/user/{username}",
        positive_markers=('class="header-title"',),
        negative_markers=("User not found", "Page Not Found"),
        min_length=2,
        max_length=15,
        regex_pattern=r"^[a-zA-Z][a-zA-Z0-9_-]*$",
    ),
    PlatformRule(
        name="Behance",
        category="Creative",
        url_template="https://www.behance.net/{username}",
        check_url_template="https://www.behance.net/{username}",
        positive_markers=('class="Profile-', 'property="og:title"'),
        negative_markers=("Oops! We can’t seem to find the page",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Dribbble",
        category="Creative",
        url_template="https://dribbble.com/{username}",
        check_url_template="https://dribbble.com/{username}",
        positive_markers=("data-user-id=", 'class="hero-profile'),
        negative_markers=("Page Not Found",),
        min_length=1,
        max_length=30,
    ),
    PlatformRule(
        name="Flickr",
        category="Creative",
        url_template="https://www.flickr.com/people/{username}/",
        check_url_template="https://www.flickr.com/people/{username}/",
        positive_markers=('class="person-head', 'class="profile-section'),
        negative_markers=("Page Not Found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Vimeo",
        category="Creative",
        url_template="https://vimeo.com/{username}",
        check_url_template="https://vimeo.com/{username}",
        positive_markers=('class="profile_header"', "data-user-id"),
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Imgur",
        category="Creative",
        url_template="https://imgur.com/user/{username}",
        check_url_template="https://imgur.com/user/{username}",
        positive_markers=('class="ProfileHeader"', 'class="account-user-name"'),
        negative_markers=("404 - Not Found", "Page Not Found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Dailymotion",
        category="Creative",
        url_template="https://www.dailymotion.com/{username}",
        check_url_template="https://www.dailymotion.com/{username}",
        positive_markers=('class="channel-header"',),
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Unsplash",
        category="Creative",
        url_template="https://unsplash.com/@{username}",
        check_url_template="https://unsplash.com/@{username}",
        positive_markers=('property="og:title"',),
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="DeviantArt",
        category="Creative",
        url_template="https://www.deviantart.com/{username}",
        check_url_template="https://www.deviantart.com/{username}",
        positive_markers=('data-hook="user_avatar"', 'property="og:title"'),
        negative_markers=("Deactivated Account", "404 Not Found"),
        min_length=1,
        max_length=30,
    ),
    PlatformRule(
        name="OpenStreetMap",
        category="Community",
        url_template="https://www.openstreetmap.org/user/{username}",
        check_url_template="https://www.openstreetmap.org/user/{username}",
        positive_markers=("Mapper since",),
        negative_markers=("does not exist",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Wikipedia",
        category="Community",
        url_template="https://en.wikipedia.org/wiki/User:{username}",
        check_url_template="https://en.wikipedia.org/wiki/User:{username}",
        positive_markers=('id="firstHeading"',),
        negative_markers=("User account does not exist",),
        min_length=1,
        max_length=50,
    ),
    PlatformRule(
        name="Goodreads",
        category="Community",
        url_template="https://www.goodreads.com/{username}",
        check_url_template="https://www.goodreads.com/{username}",
        positive_markers=('class="userProfileName"',),
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Instructables",
        category="Community",
        url_template="https://www.instructables.com/member/{username}/",
        check_url_template="https://www.instructables.com/member/{username}/",
        positive_markers=('class="profile-header"',),
        negative_markers=("404: Not Found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="ProductHunt",
        category="Community",
        url_template="https://www.producthunt.com/@{username}",
        check_url_template="https://www.producthunt.com/@{username}",
        positive_markers=('data-test="user-profile"', "Product Hunt"),
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="BuyMeACoffee",
        category="Community",
        url_template="https://www.buymeacoffee.com/{username}",
        check_url_template="https://www.buymeacoffee.com/{username}",
        positive_markers=("app-creator-profile", "creator-title"),
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Patreon",
        category="Community",
        url_template="https://www.patreon.com/{username}",
        check_url_template="https://www.patreon.com/{username}",
        positive_markers=('"page_name":', '"patron_count":'),
        negative_markers=("404 Not Found", "Page Not Found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Pastebin",
        category="Community",
        url_template="https://pastebin.com/u/{username}",
        check_url_template="https://pastebin.com/u/{username}",
        positive_markers=('class="user-profile"', 'class="user-name"'),
        negative_markers=("Not Found (#404)", "Page Not Found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Wattpad",
        category="Community",
        url_template="https://www.wattpad.com/user/{username}",
        check_url_template="https://www.wattpad.com/user/{username}",
        positive_markers=('class="profile-header"', "data-author="),
        negative_markers=("User not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Flipboard",
        category="Community",
        url_template="https://flipboard.com/@{username}",
        check_url_template="https://flipboard.com/@{username}",
        positive_markers=('class="profile-header"', "data-user="),
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="TripAdvisor",
        category="Community",
        url_template="https://www.tripadvisor.com/Profile/{username}",
        check_url_template="https://www.tripadvisor.com/Profile/{username}",
        positive_markers=('class="profile-header"',),
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Gitea",
        category="Dev",
        url_template="https://gitea.com/{username}",
        check_url_template="https://gitea.com/api/v1/users/{username}",
        is_json=True,
        json_verify_key="id",
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Gitee",
        category="Dev",
        url_template="https://gitee.com/{username}",
        check_url_template="https://gitee.com/api/v5/users/{username}",
        is_json=True,
        json_verify_key="id",
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Launchpad",
        category="Dev",
        url_template="https://launchpad.net/~{username}",
        check_url_template="https://launchpad.net/~{username}",
        min_length=1,
        max_length=40,
        regex_pattern=r"^[a-zA-Z0-9][a-zA-Z0-9+.-]*$",
    ),
    PlatformRule(
        name="Codeforces",
        category="Dev",
        url_template="https://codeforces.com/profile/{username}",
        check_url_template="https://codeforces.com/api/user.info?handles={username}",
        is_json=True,
        json_verify_key="result",
        min_length=3,
        max_length=24,
    ),
    PlatformRule(
        name="Codewars",
        category="Dev",
        url_template="https://www.codewars.com/users/{username}",
        check_url_template="https://www.codewars.com/api/v1/users/{username}",
        is_json=True,
        json_verify_key="id",
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="AtCoder",
        category="Dev",
        url_template="https://atcoder.jp/users/{username}",
        check_url_template="https://atcoder.jp/api/users/exists/{username}",
        positive_markers=("true",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Daily.dev",
        category="Dev",
        url_template="https://app.daily.dev/{username}",
        check_url_template="https://app.daily.dev/{username}",
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="WakaTime",
        category="Dev",
        url_template="https://wakatime.com/@{username}",
        check_url_template="https://wakatime.com/@{username}",
        negative_markers=("Page Not Found", "404: Not Found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Scratch",
        category="Dev",
        url_template="https://scratch.mit.edu/users/{username}",
        check_url_template="https://api.scratch.mit.edu/users/{username}",
        is_json=True,
        json_verify_key="id",
        min_length=3,
        max_length=20,
    ),
    PlatformRule(
        name="SourceHut",
        category="Dev",
        url_template="https://sr.ht/~{username}",
        check_url_template="https://sr.ht/~{username}",
        positive_markers=("<title>~", "meta.sr.ht"),
        negative_markers=("Not Found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Devpost",
        category="Dev",
        url_template="https://devpost.com/{username}",
        check_url_template="https://devpost.com/{username}",
        positive_markers=('class="user-profile"', "data-user-id"),
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Crowdin",
        category="Dev",
        url_template="https://crowdin.com/profile/{username}",
        check_url_template="https://crowdin.com/profile/{username}",
        positive_markers=('class="profile-header"',),
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Hex.pm",
        category="Dev",
        url_template="https://hex.pm/users/{username}",
        check_url_template="https://hex.pm/users/{username}",
        negative_markers=("page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="LuaRocks",
        category="Dev",
        url_template="https://luarocks.org/modules/{username}",
        check_url_template="https://luarocks.org/modules/{username}",
        negative_markers=("Not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Coderwall",
        category="Dev",
        url_template="https://coderwall.com/{username}",
        check_url_template="https://coderwall.com/{username}",
        negative_markers=("Page Not Found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Duolingo",
        category="Learning",
        url_template="https://www.duolingo.com/profile/{username}",
        check_url_template="https://www.duolingo.com/2017-06-30/users?username={username}",
        is_json=True,
        json_verify_key="users",
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Carrd",
        category="Social",
        url_template="https://{username}.carrd.co",
        check_url_template="https://{username}.carrd.co",
        negative_markers=("could not be found", "Page not found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Ko-fi",
        category="Community",
        url_template="https://ko-fi.com/{username}",
        check_url_template="https://ko-fi.com/{username}",
        positive_markers=('class="profile-', "data-profile-id"),
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Gumroad",
        category="Community",
        url_template="https://{username}.gumroad.com",
        check_url_template="https://{username}.gumroad.com",
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Hashnode",
        category="Dev",
        url_template="https://hashnode.com/@{username}",
        check_url_template="https://hashnode.com/@{username}",
        negative_markers=("Available for</h2>", "Page not found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Lobsters",
        category="Dev",
        url_template="https://lobste.rs/u/{username}",
        check_url_template="https://lobste.rs/u/{username}",
        positive_markers=('class="user-profile"', 'class="username"'),
        negative_markers=("404 Not Found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="MyAnimeList",
        category="Social",
        url_template="https://myanimelist.net/profile/{username}",
        check_url_template="https://myanimelist.net/profile/{username}",
        negative_markers=("has deleted their account", "not found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="AniList",
        category="Social",
        url_template="https://anilist.co/user/{username}",
        check_url_template="https://anilist.co/user/{username}",
        negative_markers=("Not Found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Kitsu",
        category="Social",
        url_template="https://kitsu.app/users/{username}",
        check_url_template="https://kitsu.app/api/edge/users?filter[slug]={username}",
        is_json=True,
        json_verify_key="data",
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Letterboxd",
        category="Social",
        url_template="https://letterboxd.com/{username}/",
        check_url_template="https://letterboxd.com/{username}/",
        negative_markers=("Letterboxd - Not Found", "Page not found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Trakt",
        category="Social",
        url_template="https://trakt.tv/users/{username}",
        check_url_template="https://forums.trakt.tv/u/{username}.json",
        is_json=True,
        json_verify_key="user",
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Habr",
        category="Dev",
        url_template="https://habr.com/en/users/{username}/",
        check_url_template="https://habr.com/en/users/{username}/",
        positive_markers=('class="tm-user-info"',),
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="ArtStation",
        category="Creative",
        url_template="https://www.artstation.com/{username}",
        check_url_template="https://www.artstation.com/{username}",
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Figma",
        category="Creative",
        url_template="https://www.figma.com/@{username}",
        check_url_template="https://www.figma.com/@{username}",
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Giphy",
        category="Creative",
        url_template="https://giphy.com/{username}",
        check_url_template="https://giphy.com/{username}",
        positive_markers=('class="channel-header"', 'property="og:title"'),
        negative_markers=("404 Not Found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Redbubble",
        category="Creative",
        url_template="https://www.redbubble.com/people/{username}",
        check_url_template="https://www.redbubble.com/people/{username}",
        negative_markers=("Page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Osu!",
        category="Gaming",
        url_template="https://osu.ppy.sh/users/{username}",
        check_url_template="https://osu.ppy.sh/users/{username}",
        positive_markers=('property="og:title"',),
        negative_markers=("404 Not Found", "Page not found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="VRChat",
        category="Gaming",
        url_template="https://vrchat.com/home/user/{username}",
        check_url_template="https://ask.vrchat.com/u/{username}.json",
        is_json=True,
        json_verify_key="user",
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="NexusMods",
        category="Gaming",
        url_template="https://www.nexusmods.com/users/{username}",
        check_url_template="https://www.nexusmods.com/users/{username}",
        positive_markers=('class="profile-header"',),
        negative_markers=("404 Not Found", "Page not found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Bandcamp",
        category="Music",
        url_template="https://{username}.bandcamp.com",
        check_url_template="https://{username}.bandcamp.com",
        negative_markers=("Sorry, that something isn’t here.",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Audiomack",
        category="Music",
        url_template="https://audiomack.com/{username}",
        check_url_template="https://audiomack.com/{username}",
        negative_markers=("Page Not Found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Discogs",
        category="Music",
        url_template="https://www.discogs.com/user/{username}",
        check_url_template="https://www.discogs.com/user/{username}",
        negative_markers=("404 Not Found", "User not found"),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="ReverbNation",
        category="Music",
        url_template="https://www.reverbnation.com/{username}",
        check_url_template="https://www.reverbnation.com/{username}",
        negative_markers=("doesn't exist",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="OpenSea",
        category="Finance",
        url_template="https://opensea.io/{username}",
        check_url_template="https://opensea.io/{username}",
        negative_markers=("This page could not be found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="TradingView",
        category="Finance",
        url_template="https://www.tradingview.com/u/{username}/",
        check_url_template="https://www.tradingview.com/u/{username}/",
        positive_markers=('class="tv-profile', 'class="profile-header'),
        negative_markers=("page not found",),
        min_length=1,
        max_length=40,
    ),
    PlatformRule(
        name="Tinder",
        category="Dating",
        url_template="https://tinder.com/@{username}",
        custom_checker=check_tinder_user,
        min_length=3,
        max_length=30,
    ),
]
