from sigit.services.email.email_recon.custom_checkers import (
    check_facebook,
    check_instagram,
    check_lespark,
    check_meeff,
    check_threads,
)
from sigit.services.email.email_recon.models import EmailPlatformRule

EMAIL_PLATFORMS: list[EmailPlatformRule] = [
    EmailPlatformRule(
        name="GitHub",
        category="Dev",
        url="https://github.com",
        check_url_template="https://api.github.com/search/users?q={email}+in:email",
        headers={"Accept": "application/vnd.github.v3+json"},
        positive_markers=(
            '"total_count":1',
            '"total_count":2',
            '"total_count":3',
            '"total_count":4',
        ),
        negative_markers=('"total_count":0',),
    ),
    EmailPlatformRule(
        name="Gravatar",
        category="Dev",
        url="https://gravatar.com",
        check_url_template="https://www.gravatar.com/avatar/{email_hash}?d=404",
        hash_method="sha256",
        taken_codes=(200,),
        available_codes=(404,),
    ),
    EmailPlatformRule(
        name="Atlassian",
        category="Dev",
        url="https://id.atlassian.com",
        check_url_template="https://id.atlassian.com/rest/check-username",
        method="POST",
        headers={"Content-Type": "application/json", "Referer": "https://id.atlassian.com/login"},
        json_payload={"username": "{email}"},
        positive_markers=('"action":"no_action"', '"action":"redirect"'),
        negative_markers=('"action":"signup"',),
    ),
    EmailPlatformRule(
        name="WordPress",
        category="Dev",
        url="https://wordpress.com",
        check_url_template="https://public-api.wordpress.com/rest/v1.1/users/{email}/auth-options?http_envelope=1",
        positive_markers=('"code":200', "email_login_not_allowed"),
        negative_markers=('"code":400', "unknown_user"),
    ),
    EmailPlatformRule(
        name="Codecademy",
        category="Dev",
        url="https://codecademy.com",
        check_url_template="https://www.codecademy.com/profiles",
        method="POST",
        json_payload={"user": {"email": "{email}"}},
        positive_markers=("has already been taken",),
        negative_markers=("can't be blank",),
    ),
    EmailPlatformRule(
        name="CodePen",
        category="Dev",
        url="https://codepen.io",
        check_url_template="https://codepen.io/accounts/validate",
        method="POST",
        data_payload={"attribute": "email", "value": "{email}", "context": "user"},
        positive_markers=("already taken", "taken"),
        negative_markers=("true", "available"),
    ),
    EmailPlatformRule(
        name="Codewars",
        category="Dev",
        url="https://codewars.com",
        check_url_template="https://www.codewars.com/join",
        method="POST",
        params={"language": "javascript"},
        data_payload={"user[email]": "{email}", "_method": "patch", "utf8": "\u2713"},
        positive_markers=("is already taken",),
        negative_markers=("can&#39;t be blank",),
    ),
    EmailPlatformRule(
        name="devRant",
        category="Dev",
        url="https://devrant.com",
        check_url_template="https://devrant.com/api/users",
        method="POST",
        data_payload={"app": "3", "email": "{email}"},
        positive_markers=("Email already exists",),
        negative_markers=("Missing username",),
    ),
    EmailPlatformRule(
        name="Envato",
        category="Dev",
        url="https://elements.envato.com",
        check_url_template="https://account.envato.com/api/public/validate_email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"status":"taken"', "taken"),
        negative_markers=('"status":"available"', "available"),
    ),
    EmailPlatformRule(
        name="HackerEarth",
        category="Dev",
        url="https://www.hackerearth.com",
        check_url_template="https://www.hackerearth.com/api/v1/sparta/auth/signup/",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("already registered", "already exists"),
        negative_markers=("Enter password", "Enter name"),
    ),
    EmailPlatformRule(
        name="HackerRank",
        category="Dev",
        url="https://www.hackerrank.com",
        check_url_template="https://www.hackerrank.com/auth/valid_email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("already taken", '"status":false'),
        negative_markers=('"status":true', "true"),
    ),
    EmailPlatformRule(
        name="HowToGeek",
        category="Dev",
        url="https://www.howtogeek.com",
        check_url_template="https://www.howtogeek.com/check-user-exists/?email={encoded_email}",
        positive_markers=("true", "exists"),
        negative_markers=("false",),
    ),
    EmailPlatformRule(
        name="HuggingFace",
        category="Dev",
        url="https://huggingface.co",
        check_url_template="https://huggingface.co/api/check-user-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("true", "exists", "taken"),
        negative_markers=("false", "available"),
    ),
    EmailPlatformRule(
        name="LuaRocks",
        category="Dev",
        url="https://luarocks.org",
        check_url_template="https://luarocks.org/forgot_password",
        method="POST",
        data_payload={"email": "{email}"},
        positive_markers=("Password reset instructions have been sent",),
        negative_markers=("User not found",),
    ),
    EmailPlatformRule(
        name="Medium",
        category="Dev",
        url="https://medium.com",
        check_url_template="https://medium.com/_/graphql",
        method="POST",
        json_payload={
            "operationName": "CheckEmail",
            "variables": {"email": "{email}"},
            "query": "query CheckEmail($email: String!) { isEmailUsed(email: $email) }",
        },
        positive_markers=('"isEmailUsed":true',),
        negative_markers=('"isEmailUsed":false',),
    ),
    EmailPlatformRule(
        name="RubyGems",
        category="Dev",
        url="https://rubygems.org",
        check_url_template="https://rubygems.org/users",
        method="POST",
        data_payload={"user[email]": "{email}"},
        positive_markers=("has already been taken",),
        negative_markers=("Password can't be blank",),
    ),
    EmailPlatformRule(
        name="Wix",
        category="Dev",
        url="https://wix.com",
        check_url_template="https://users.wix.com/wix-users/v1/userAccountsByEmail",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("USER_ALREADY_EXISTS", "already exists"),
        negative_markers=("USER_NOT_FOUND", "not found"),
    ),
    EmailPlatformRule(
        name="Wondershare",
        category="Dev",
        url="https://wondershare.com",
        check_url_template="https://accounts.wondershare.com/api/v3/account/inspect",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"status":1', '"account_exists":true'),
        negative_markers=('"status":0', '"account_exists":false'),
    ),
    EmailPlatformRule(
        name="XDA Developers",
        category="Dev",
        url="https://xda-developers.com",
        check_url_template="https://www.xda-developers.com/check-user-exists/?email={encoded_email}",
        positive_markers=("true", "exists"),
        negative_markers=("false",),
    ),
    EmailPlatformRule(
        name="Adobe",
        category="Creator",
        url="https://adobe.com",
        check_url_template="https://auth.services.adobe.com/signin/v2/users/accounts",
        method="POST",
        headers={"Content-Type": "application/json", "x-adobe-client-id": "adobedotcom2"},
        json_payload={"username": "{email}"},
        positive_markers=('"status":"FOUND"', "FOUND", '"accountExists":true'),
        negative_markers=('"status":"NOT_FOUND"', "NOT_FOUND", '"accountExists":false'),
    ),
    EmailPlatformRule(
        name="BuyMeACoffee",
        category="Creator",
        url="https://buymeacoffee.com",
        check_url_template="https://app.buymeacoffee.com/api/v1/email/login",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("Enter password", "otp_sent", '"status":true', '"success":true'),
        negative_markers=("User not found", "user_not_found", "No account found"),
    ),
    EmailPlatformRule(
        name="Canva",
        category="Creator",
        url="https://canva.com",
        check_url_template="https://www.canva.com/_ajax/authnflow/user-authentication-methods",
        method="POST",
        headers={"Content-Type": "application/json", "Referer": "https://www.canva.com/login"},
        json_payload={"email": "{email}"},
        positive_markers=('"result":"SUCCESS"', "PASSWORD", "SIGN_IN"),
        negative_markers=('"result":"SIGNUP"', "SIGN_UP"),
    ),
    EmailPlatformRule(
        name="Figma",
        category="Creator",
        url="https://figma.com",
        check_url_template="https://www.figma.com/api/session/available_auth_methods?email={encoded_email}&form_intent=sign_up",
        positive_markers=('"sign_in"', '"email"'),
        negative_markers=('"available_methods":[]',),
    ),
    EmailPlatformRule(
        name="Flickr",
        category="Creator",
        url="https://flickr.com",
        check_url_template="https://identity.flickr.com/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true', '"taken":true'),
        negative_markers=('"exists":false', '"taken":false'),
    ),
    EmailPlatformRule(
        name="Kick",
        category="Creator",
        url="https://kick.com",
        check_url_template="https://kick.com/api/v1/signup/verify/email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("is already taken", "already been taken"),
        negative_markers=("is available", "valid"),
    ),
    EmailPlatformRule(
        name="Leanpub",
        category="Creator",
        url="https://leanpub.com",
        check_url_template="https://leanpub.com/password_resets",
        method="POST",
        data_payload={"email": "{email}"},
        positive_markers=("Email sent with password reset instructions", "reset instructions"),
        negative_markers=("Email address not found", "not found"),
    ),
    EmailPlatformRule(
        name="Patreon",
        category="Creator",
        url="https://patreon.com",
        check_url_template="https://www.patreon.com/api/auth",
        method="POST",
        headers={"Content-Type": "application/json"},
        json_payload={"data": {"type": "user", "attributes": {"email": "{email}"}}},
        positive_markers=('"exists":true', "exists"),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Payhip",
        category="Creator",
        url="https://payhip.com",
        check_url_template="https://payhip.com/auth/forgot_password_buyer_ajax",
        method="POST",
        data_payload={"email": "{email}"},
        positive_markers=('"status":"success"', "Reset password link sent"),
        negative_markers=("We could not find an account", "not find"),
    ),
    EmailPlatformRule(
        name="Threadless",
        category="Creator",
        url="https://threadless.com",
        check_url_template="https://www.threadless.com/members/forgot_password",
        method="POST",
        data_payload={"email": "{email}"},
        positive_markers=("Instructions have been sent", "email has been sent"),
        negative_markers=("We couldn't find an account", "not found"),
    ),
    EmailPlatformRule(
        name="Wisio",
        category="Creator",
        url="https://wisio.com",
        check_url_template="https://www.wisio.com/api/users/check-email?email={encoded_email}",
        positive_markers=('"exists":true', '"isAvailable":false'),
        negative_markers=('"exists":false', '"isAvailable":true'),
    ),
    EmailPlatformRule(
        name="Coursera",
        category="Learning",
        url="https://coursera.org",
        check_url_template="https://www.coursera.org/api/userAccounts.v1",
        method="POST",
        params={"action": "getLoginMethods", "email": "{email}"},
        headers={
            "X-Requested-With": "XMLHttpRequest",
            "Referer": "https://www.coursera.org/?authMode=signup",
        },
        json_payload={},
        positive_markers=('"loginMethods":["', '"loginMethods": ["'),
        negative_markers=('"loginMethods":[]', '"loginMethods": []'),
    ),
    EmailPlatformRule(
        name="Duolingo",
        category="Learning",
        url="https://duolingo.com",
        check_url_template="https://www.duolingo.com/2017-06-30/users?email={encoded_email}",
        headers={"Referer": "https://www.duolingo.com/"},
        positive_markers=('"users":[{"', '"username":'),
        negative_markers=('"users":[]',),
    ),
    EmailPlatformRule(
        name="Babbel",
        category="Learning",
        url="https://babbel.com",
        check_url_template="https://api.babbel.io/gamma/v2/en/users/",
        method="POST",
        headers={"Content-Type": "application/json; charset=UTF-8"},
        json_payload={
            "user": {
                "email": "{email}",
                "password": "",
                "firstname": "user",
                "learn_language_alpha3": "QMS",
            }
        },
        positive_markers=('"attribute":"email"', "taken"),
        negative_markers=("can't be blank",),
    ),
    EmailPlatformRule(
        name="ClassDojo",
        category="Learning",
        url="https://classdojo.com",
        check_url_template="https://home.classdojo.com/api/user/checkEmail?email={encoded_email}",
        positive_markers=('"isAvailable":false', '"exists":true'),
        negative_markers=('"isAvailable":true', '"exists":false'),
    ),
    EmailPlatformRule(
        name="Allen",
        category="Learning",
        url="https://allen.in",
        check_url_template="https://api.allen.in/auth/v1/users/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true', '"user_exists":true'),
        negative_markers=('"exists":false', '"user_exists":false'),
    ),
    EmailPlatformRule(
        name="Asafeer",
        category="Learning",
        url="https://3asafeer.com",
        check_url_template="https://api.3asafeer.com/api/v1/auth/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"status":true', '"registered":true'),
        negative_markers=('"status":false', '"registered":false'),
    ),
    EmailPlatformRule(
        name="AslBloom",
        category="Learning",
        url="https://aslbloom.com",
        check_url_template="https://api.aslbloom.com/v1/users/verify",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="BNR Languages",
        category="Learning",
        url="https://bnrlanguages.com",
        check_url_template="https://api.bnrlanguages.com/v1/account/exists",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Bunpo",
        category="Learning",
        url="https://bunpo.app",
        check_url_template="https://api.bunpo.app/v1/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"registered":true', '"exists":true'),
        negative_markers=('"registered":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="CakeApp",
        category="Learning",
        url="https://mycake.me",
        check_url_template="https://api.mycake.me/v1/users/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"is_member":true', '"exists":true'),
        negative_markers=('"is_member":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="Cambly",
        category="Learning",
        url="https://cambly.com",
        check_url_template="https://www.cambly.com/api/users/check_email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"inUse":true', '"exists":true'),
        negative_markers=('"inUse":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="DuoCards",
        category="Learning",
        url="https://duocards.org",
        check_url_template="https://api.duocards.org/v1/auth/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Hanzii",
        category="Learning",
        url="https://hanzii.net",
        check_url_template="https://api.hanzii.net/api/password/reset",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("success", "code sent"),
        negative_markers=("not found", "does not exist"),
    ),
    EmailPlatformRule(
        name="HelloChinese",
        category="Learning",
        url="https://hellochinese.cc",
        check_url_template="https://api.hellochinese.cc/v1/user/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="HeyJapan",
        category="Learning",
        url="https://heyjapan.net",
        check_url_template="https://v2.heyjapan.net/password/passwordCode",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"status":200', '"success":true'),
        negative_markers=('"status":400', '"status":404'),
    ),
    EmailPlatformRule(
        name="JetPunk",
        category="Learning",
        url="https://jetpunk.com",
        check_url_template="https://www.jetpunk.com/check-email.php?email={encoded_email}",
        positive_markers=("taken", "already registered"),
        negative_markers=("available",),
    ),
    EmailPlatformRule(
        name="Linga",
        category="Learning",
        url="https://linga.io",
        check_url_template="https://api.linga.io/v1/user/exists",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="LingQ",
        category="Learning",
        url="https://lingq.com",
        check_url_template="https://www.lingq.com/api/v3/users/validate-email/",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("already in use", "taken"),
        negative_markers=("valid", "available"),
    ),
    EmailPlatformRule(
        name="Memrise",
        category="Learning",
        url="https://memrise.com",
        check_url_template="https://www.memrise.com/api/users/check_email/?email={encoded_email}",
        positive_markers=('"exists":true', '"in_use":true'),
        negative_markers=('"exists":false', '"in_use":false'),
    ),
    EmailPlatformRule(
        name="Mondly",
        category="Learning",
        url="https://mondly.com",
        check_url_template="https://api.mondlylanguages.com/v1/users/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="ProgrammingHub",
        category="Learning",
        url="https://programminghub.io",
        check_url_template="https://server.programminghub.io/api/v1/user/exists",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Quizlet",
        category="Learning",
        url="https://quizlet.com",
        check_url_template="https://quizlet.com/webapi/3.4/users/lookup?email={encoded_email}",
        headers={"X-Requested-With": "XMLHttpRequest"},
        positive_markers=('"isTaken":true', '"exists":true'),
        negative_markers=('"isTaken":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="Speak",
        category="Learning",
        url="https://usespeak.com",
        check_url_template="https://api.usespeak.com/v1/users/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Speakly",
        category="Learning",
        url="https://speakly.me",
        check_url_template="https://api.speakly.me/v1/auth/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="TalkMe",
        category="Learning",
        url="https://talkme.ai",
        check_url_template="https://api.talkme.ai/v1/users/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="TalkPal",
        category="Learning",
        url="https://talkpal.ai",
        check_url_template="https://api.talkpal.ai/api/v1/auth/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"registered":true', '"exists":true'),
        negative_markers=('"registered":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="Chess.com",
        category="Gaming",
        url="https://chess.com",
        check_url_template="https://www.chess.com/rpc/chesscom.authentication.v1.EmailValidationService/Validate",
        method="POST",
        headers={
            "Content-Type": "application/json",
            "Referer": "https://www.chess.com/register",
            "connect-protocol-version": "1",
        },
        json_payload={"email": "{email}"},
        positive_markers=("EMAIL_STATUS_TAKEN",),
        negative_markers=("EMAIL_STATUS_AVAILABLE",),
    ),
    EmailPlatformRule(
        name="AddictingGames",
        category="Gaming",
        url="https://addictinggames.com",
        check_url_template="https://api.addictinggames.com/v1/users/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"taken":true', '"exists":true'),
        negative_markers=('"taken":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="CrazyGames",
        category="Gaming",
        url="https://crazygames.com",
        check_url_template="https://api.crazygames.com/v2/users/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Medal.tv",
        category="Gaming",
        url="https://medal.tv",
        check_url_template="https://api-presence.medal.tv/v1/account/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"taken":true', '"exists":true'),
        negative_markers=('"taken":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="StackB",
        category="Gaming",
        url="https://stackb.net",
        check_url_template="https://stackb.net/api/users/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Spotify",
        category="Music",
        url="https://spotify.com",
        check_url_template="https://spclient.wg.spotify.com/signup/public/v1/account?validate=1&email={encoded_email}",
        positive_markers=('"status":20', '"status": 20', "already registered"),
        negative_markers=('"status":1', '"status": 1'),
    ),
    EmailPlatformRule(
        name="Deezer",
        category="Music",
        url="https://deezer.com",
        check_url_template="https://www.deezer.com/ajax/action.php",
        method="POST",
        data_payload={"service": "user.checkEmail", "email": "{email}"},
        positive_markers=('"valid":false', "already taken"),
        negative_markers=('"valid":true',),
    ),
    EmailPlatformRule(
        name="Mixcloud",
        category="Music",
        url="https://mixcloud.com",
        check_url_template="https://www.mixcloud.com/check-email/",
        method="POST",
        data_payload={"email": "{email}"},
        positive_markers=("taken", "already in use"),
        negative_markers=("available", "valid"),
    ),
    EmailPlatformRule(
        name="Gaana",
        category="Music",
        url="https://gaana.com",
        check_url_template="https://jsso.indiatimes.com/sso/crossapp/identity/web/checkUser?email={encoded_email}",
        positive_markers=('"userExists":"true"', '"userExists":true'),
        negative_markers=('"userExists":"false"', '"userExists":false'),
    ),
    EmailPlatformRule(
        name="JioSaavn",
        category="Music",
        url="https://jiosaavn.com",
        check_url_template="https://www.saavn.com/api.php?__call=user.checkUserExists&email={encoded_email}",
        positive_markers=('"exists":true', '"status":"success"'),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Flipboard",
        category="News",
        url="https://flipboard.com",
        check_url_template="https://fbprod.flipboard.com/v1/flipboard/checkEmail/0?email={encoded_email}",
        positive_markers=('"taken":true', '"exists":true'),
        negative_markers=('"taken":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="Fox News",
        category="News",
        url="https://foxnews.com",
        check_url_template="https://id.fox.com/status/v1/status?email={encoded_email}",
        positive_markers=('"status":"EXISTS"', '"status": "EXISTS"'),
        negative_markers=('"status":"NOT_EXISTS"', '"status": "NOT_EXISTS"'),
    ),
    EmailPlatformRule(
        name="CNN",
        category="News",
        url="https://cnn.com",
        check_url_template="https://api.cnn.com/user/check?email={encoded_email}",
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="BBC",
        category="News",
        url="https://bbc.com",
        check_url_template="https://account.bbc.com/check-email?email={encoded_email}",
        positive_markers=('"registered":true', '"exists":true'),
        negative_markers=('"registered":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="Al Jazeera",
        category="News",
        url="https://aljazeera.com",
        check_url_template="https://api.aljazeera.com/v1/auth/check?email={encoded_email}",
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="IndiaTimes",
        category="News",
        url="https://timesofindia.com",
        check_url_template="https://jsso.indiatimes.com/sso/crossapp/identity/web/checkUser?loginId={encoded_email}",
        positive_markers=('"userExists":"true"', '"userExists":true'),
        negative_markers=('"userExists":"false"', '"userExists":false'),
    ),
    EmailPlatformRule(
        name="Disqus",
        category="Social",
        url="https://disqus.com",
        check_url_template="https://disqus.com/api/3.0/users/checkEmail.json?email={encoded_email}",
        positive_markers=('"registered":true', '"exists":true'),
        negative_markers=('"registered":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="Nextdoor",
        category="Social",
        url="https://nextdoor.com",
        check_url_template="https://auth.nextdoor.com/v2/token",
        method="POST",
        data_payload={"username": "{email}", "grant_type": "password"},
        positive_markers=("invalid_grant", "Invalid credentials"),
        negative_markers=("user_not_found", "User does not exist"),
    ),
    EmailPlatformRule(
        name="StackOverflow",
        category="Social",
        url="https://stackoverflow.com",
        check_url_template="https://stackoverflow.com/users/login",
        method="POST",
        data_payload={"email": "{email}"},
        positive_markers=("No account found", "Password is required"),
        negative_markers=("Account does not exist",),
    ),
    EmailPlatformRule(
        name="Pinterest",
        category="Social",
        url="https://pinterest.com",
        check_url_template="https://www.pinterest.com/_ngjs/resource/EmailExistsResource/get/?data=%7B%22options%22%3A%7B%22email%22%3A%22{encoded_email}%22%7D%7D",
        positive_markers=('"data":true', '"data": true'),
        negative_markers=('"data":false', '"data": false'),
    ),
    EmailPlatformRule(
        name="Tumblr",
        category="Social",
        url="https://tumblr.com",
        check_url_template="https://www.tumblr.com/svc/account/register",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("already have an account", "already taken"),
        negative_markers=("valid", "available"),
    ),
    EmailPlatformRule(
        name="Plurk",
        category="Social",
        url="https://plurk.com",
        check_url_template="https://www.plurk.com/Users/isEmailAvailable?email={encoded_email}",
        positive_markers=('"available":false', '"available": false'),
        negative_markers=('"available":true', '"available": true'),
    ),
    EmailPlatformRule(
        name="Slowly",
        category="Social",
        url="https://slowly.app",
        check_url_template="https://api.slowly.app/v1/auth/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Superlive",
        category="Social",
        url="https://superlive.io",
        check_url_template="https://api.superlive.io/v1/user/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Meeff",
        category="Dating",
        url="https://meeff.com",
        custom_checker=check_meeff,
    ),
    EmailPlatformRule(
        name="LesPark",
        category="Dating",
        url="https://lespark.cn",
        custom_checker=check_lespark,
    ),
    EmailPlatformRule(
        name="MeWe",
        category="Social",
        url="https://mewe.com",
        check_url_template="https://mewe.com/api/v2/auth/checkEmail?email={encoded_email}",
        positive_markers=('"exists":true', '"available":false'),
        negative_markers=('"exists":false', '"available":true'),
    ),
    EmailPlatformRule(
        name="Locket",
        category="Social",
        url="https://locket.camera",
        check_url_template="https://api.locket.camera/v1/users/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="LoveNudge",
        category="Dating",
        url="https://lovenudgeapp.com",
        check_url_template="https://api.lovenudgeapp.com/api/register/check?email={encoded_email}",
        positive_markers=('"is_registered":true', '"is_registered": 1'),
        negative_markers=('"is_registered":false', '"is_registered": 0'),
    ),
    EmailPlatformRule(
        name="CoupleJoy",
        category="Dating",
        url="https://couplejoy.app",
        check_url_template="https://api.couplejoy.app/v1/auth/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Whering",
        category="Social",
        url="https://whering.co.uk",
        check_url_template="https://api.whering.co.uk/api/v1/auth/check-email/",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true', '"is_available":false'),
        negative_markers=('"exists":false', '"is_available":true'),
    ),
    EmailPlatformRule(
        name="X",
        category="Social",
        url="https://x.com",
        check_url_template="https://api.x.com/i/users/email_available.json?email={encoded_email}",
        positive_markers=('"taken":true', '"taken": true'),
        negative_markers=('"taken":false', '"taken": false'),
    ),
    EmailPlatformRule(
        name="Instagram",
        category="Social",
        url="https://instagram.com",
        custom_checker=check_instagram,
    ),
    EmailPlatformRule(
        name="Facebook",
        category="Social",
        url="https://facebook.com",
        custom_checker=check_facebook,
    ),
    EmailPlatformRule(
        name="Threads",
        category="Social",
        url="https://threads.net",
        custom_checker=check_threads,
    ),
    EmailPlatformRule(
        name="AniList",
        category="Entertainment",
        url="https://anilist.co",
        check_url_template="https://anilist.co/api/v2/auth/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true', '"taken":true'),
        negative_markers=('"exists":false', '"taken":false'),
    ),
    EmailPlatformRule(
        name="Apple TV",
        category="Entertainment",
        url="https://tv.apple.com",
        check_url_template="https://idmsa.apple.com/appleauth/auth/signin/init",
        method="POST",
        headers={"Content-Type": "application/json"},
        json_payload={"accountName": "{email}"},
        positive_markers=("ACCOUNT_EXISTS", "HMAC"),
        negative_markers=("NOT_FOUND", "ACCOUNT_NOT_FOUND"),
    ),
    EmailPlatformRule(
        name="Dreame",
        category="Entertainment",
        url="https://dreame.com",
        check_url_template="https://wap-api.dreame.com/Login/loginWithEmail",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("PASSWORD_ERROR", "Password incorrect"),
        negative_markers=("USER_NOT_EXIST", "User not found"),
    ),
    EmailPlatformRule(
        name="Hoichoi",
        category="Entertainment",
        url="https://hoichoi.tv",
        check_url_template="https://api.hoichoi.tv/v1/user/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="JustWatch",
        category="Entertainment",
        url="https://justwatch.com",
        check_url_template="https://apis.justwatch.com/content/v2/auth/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true', '"isAvailable":false'),
        negative_markers=('"exists":false', '"isAvailable":true'),
    ),
    EmailPlatformRule(
        name="MyAnimeList",
        category="Entertainment",
        url="https://myanimelist.net",
        check_url_template="https://myanimelist.net/register/check_email",
        method="POST",
        data_payload={"email": "{email}"},
        positive_markers=("Email already in use", "taken"),
        negative_markers=("available", "valid"),
    ),
    EmailPlatformRule(
        name="Nebula TV",
        category="Entertainment",
        url="https://nebula.tv",
        check_url_template="https://nebula.tv/auth/registration/",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("already in use", "user with this email already exists"),
        negative_markers=("valid", "available"),
    ),
    EmailPlatformRule(
        name="Stremio",
        category="Entertainment",
        url="https://stremio.com",
        check_url_template="https://api.strem.io/api/checkEmail",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true', '"result":true'),
        negative_markers=('"exists":false', '"result":false'),
    ),
    EmailPlatformRule(
        name="SunNXT",
        category="Entertainment",
        url="https://sunnxt.net",
        check_url_template="https://api.sunnxt.net/v1/user/exists",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Weverse",
        category="Entertainment",
        url="https://weverse.io",
        check_url_template="https://account.weverse.io/api/v1/check-account",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true', '"status":"EXISTS"'),
        negative_markers=('"exists":false', '"status":"NOT_EXISTS"'),
    ),
    EmailPlatformRule(
        name="Etsy",
        category="Shopping",
        url="https://etsy.com",
        check_url_template="https://www.etsy.com/api/v3/ajax/public/users/by-identity-option?email={encoded_email}",
        positive_markers=('"is_registered":true', '"registered":true'),
        negative_markers=('"is_registered":false', '"registered":false'),
    ),
    EmailPlatformRule(
        name="Fixderma",
        category="Shopping",
        url="https://fixderma.com",
        check_url_template="https://api.fixderma.com/v1/customer/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Flipkart",
        category="Shopping",
        url="https://flipkart.com",
        check_url_template="https://www.flipkart.com/api/5/user/lookup",
        method="POST",
        json_payload={"loginId": "{email}"},
        positive_markers=('"status":"EXISTING_USER"', '"status": "EXISTING_USER"'),
        negative_markers=('"status":"NEW_USER"', '"status": "NEW_USER"'),
    ),
    EmailPlatformRule(
        name="HauteSauce",
        category="Shopping",
        url="https://hautesauce.in",
        check_url_template="https://api.hautesauce.in/v1/user/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="NaturaBuy",
        category="Shopping",
        url="https://naturabuy.fr",
        check_url_template="https://api.naturabuy.fr/v1/account/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="NykaaMan",
        category="Shopping",
        url="https://nykaaman.com",
        check_url_template="https://api.nykaaman.com/v1/auth/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"user_exists":true', '"exists":true'),
        negative_markers=('"user_exists":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="TataCliq",
        category="Shopping",
        url="https://tatacliq.com",
        check_url_template="https://api.tatadigital.com/api/v2/sso/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"isRegistered":true', '"isRegistered": true'),
        negative_markers=('"isRegistered":false', '"isRegistered": false'),
    ),
    EmailPlatformRule(
        name="Tindie",
        category="Shopping",
        url="https://tindie.com",
        check_url_template="https://www.tindie.com/api/v1/check-email/?email={encoded_email}",
        positive_markers=('"exists":true', '"taken":true'),
        negative_markers=('"exists":false', '"taken":false'),
    ),
    EmailPlatformRule(
        name="Walmart",
        category="Shopping",
        url="https://walmart.com",
        check_url_template="https://www.walmart.com/account/api/auth/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"hasAccount":true', '"accountExists":true'),
        negative_markers=('"hasAccount":false', '"accountExists":false'),
    ),
    EmailPlatformRule(
        name="Axonaut",
        category="Productivity",
        url="https://axonaut.com",
        check_url_template="https://axonaut.com/api/v1/users/check?email={encoded_email}",
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="HubSpot",
        category="Productivity",
        url="https://hubspot.com",
        check_url_template="https://api.hubspot.com/login-api/v1/check-user",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"userExists":true', '"userExists": true'),
        negative_markers=('"userExists":false', '"userExists": false'),
    ),
    EmailPlatformRule(
        name="Insightly",
        category="Productivity",
        url="https://insightly.com",
        check_url_template="https://login.insightly.com/User/CheckEmail",
        method="POST",
        data_payload={"email": "{email}"},
        positive_markers=('"exists":true', "exists"),
        negative_markers=('"exists":false', "not found"),
    ),
    EmailPlatformRule(
        name="Zoho",
        category="Productivity",
        url="https://zoho.com",
        check_url_template="https://accounts.zoho.com/signin/v2/lookup/{encoded_email}",
        positive_markers=('"status":"EXISTING_USER"', '"status": "EXISTING_USER"'),
        negative_markers=('"status":"NEW_USER"', '"status": "NEW_USER"'),
    ),
    EmailPlatformRule(
        name="Any.do",
        category="Productivity",
        url="https://any.do",
        check_url_template="https://sm-prod2.any.do/check_email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true', '"user_exists":true'),
        negative_markers=('"exists":false', '"user_exists":false'),
    ),
    EmailPlatformRule(
        name="DollarFix",
        category="Productivity",
        url="https://dollarfix.com",
        check_url_template="https://api.dollarfix.com/v1/user/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Firefox",
        category="Productivity",
        url="https://mozilla.org",
        check_url_template="https://api.accounts.firefox.com/v1/account/status",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true', '"exists": true'),
        negative_markers=('"exists":false', '"exists": false'),
    ),
    EmailPlatformRule(
        name="Moz",
        category="Productivity",
        url="https://moz.com",
        check_url_template="https://moz.com/users/check-email",
        method="POST",
        data_payload={"email": "{email}"},
        positive_markers=("already in use", "taken"),
        negative_markers=("available",),
    ),
    EmailPlatformRule(
        name="Office365",
        category="Productivity",
        url="https://office.com",
        check_url_template="https://login.microsoftonline.com/common/GetCredentialType",
        method="POST",
        headers={"Content-Type": "application/json"},
        json_payload={"username": "{email}"},
        positive_markers=('"IfExistsResult":0', '"IfExistsResult": 0'),
        negative_markers=('"IfExistsResult":1', '"IfExistsResult": 1'),
    ),
    EmailPlatformRule(
        name="AiScore",
        category="Sports",
        url="https://aiscore.com",
        check_url_template="https://api.interntp.com/v1/app/user/register",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("already registered", "User exists"),
        negative_markers=("password is required",),
    ),
    EmailPlatformRule(
        name="BeSoccer",
        category="Sports",
        url="https://besoccer.com",
        check_url_template="https://fast.okcats.com/scripts/api/api.php?action=check_email&email={encoded_email}",
        positive_markers=('"exists":1', '"exists": 1'),
        negative_markers=('"exists":0', '"exists": 0'),
    ),
    EmailPlatformRule(
        name="ESPN",
        category="Sports",
        url="https://espn.com",
        check_url_template="https://registerdisney.go.com/jgc/v6/client/ESPN-ONESITE.WEB-PROD/guest/check",
        method="POST",
        json_payload={"loginValue": "{email}"},
        positive_markers=('"status":"EXISTS"', '"status": "EXISTS"'),
        negative_markers=('"status":"AVAILABLE"', '"status": "AVAILABLE"'),
    ),
    EmailPlatformRule(
        name="Marca",
        category="Sports",
        url="https://marca.com",
        check_url_template="https://api.marca.com/v1/user/check?email={encoded_email}",
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="NBA",
        category="Sports",
        url="https://nba.com",
        check_url_template="https://identity.nba.com/api/v1/users/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true', '"registered":true'),
        negative_markers=('"exists":false', '"registered":false'),
    ),
    EmailPlatformRule(
        name="Playtomic",
        category="Sports",
        url="https://playtomic.io",
        check_url_template="https://api.app.playtomic.io/v3/auth/methods?email={encoded_email}",
        positive_markers=('"methods":["', '"methods": ["'),
        negative_markers=('"methods":[]',),
    ),
    EmailPlatformRule(
        name="UniScore",
        category="Sports",
        url="https://uniscore.com",
        check_url_template="https://api.unik8s.com/api/v2/account/auth/forgot-password?loginId={encoded_email}",
        method="POST",
        positive_markers=('"code":200', '"success":true'),
        negative_markers=('"code":404', "User not found"),
    ),
    EmailPlatformRule(
        name="EvolveYou",
        category="Fitness",
        url="https://evolveyou.app",
        check_url_template="https://fitness.evolveyouapi.com/api/v1/auth/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="Finch",
        category="Fitness",
        url="https://finchcare.com",
        check_url_template="https://api.finchcare.com/v1/user/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="FitnessBlender",
        category="Fitness",
        url="https://fitnessblender.com",
        check_url_template="https://www.fitnessblender.com/api/auth/check-email",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"taken":true', '"exists":true'),
        negative_markers=('"taken":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="MyFitnessPal",
        category="Fitness",
        url="https://myfitnesspal.com",
        check_url_template="https://www.myfitnesspal.com/api/idm/user-exists?email={encoded_email}",
        positive_markers=('"exists":true', '"exists": true'),
        negative_markers=('"exists":false', '"exists": false'),
    ),
    EmailPlatformRule(
        name="Emirates",
        category="Travel",
        url="https://emirates.com",
        check_url_template="https://www.emirates.com/api/v1/account/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"accountExists":true', '"exists":true'),
        negative_markers=('"accountExists":false', '"exists":false'),
    ),
    EmailPlatformRule(
        name="Komoot",
        category="Travel",
        url="https://komoot.com",
        check_url_template="https://api.komoot.de/v007/account/email/{encoded_email}/",
        positive_markers=('"username":', '"status":"registered"'),
        negative_markers=('"status":"not_found"',),
        taken_codes=(200,),
        available_codes=(404,),
    ),
    EmailPlatformRule(
        name="Polarsteps",
        category="Travel",
        url="https://polarsteps.com",
        check_url_template="https://www.polarsteps.com/api/users/validation/unique?email={encoded_email}",
        positive_markers=('"is_unique":false', '"is_unique": false'),
        negative_markers=('"is_unique":true', '"is_unique": true'),
    ),
    EmailPlatformRule(
        name="Skyscanner",
        category="Travel",
        url="https://skyscanner.net",
        check_url_template="https://mobile.ds.skyscanner.net/g/traveller-auth-service/account/exists",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true', '"userExists":true'),
        negative_markers=('"exists":false', '"userExists":false'),
    ),
    EmailPlatformRule(
        name="Femometer",
        category="Health",
        url="https://femometer.com",
        check_url_template="https://api.femometer.com/v1/user_location?email={encoded_email}",
        positive_markers=('"code":0', '"status":"success"'),
        negative_markers=('"code":1001', "not registered"),
    ),
    EmailPlatformRule(
        name="Glow",
        category="Health",
        url="https://glowing.com",
        check_url_template="https://account.glowing.com/a/v3/users/signup_email",
        method="POST",
        data_payload={"email": "{email}"},
        positive_markers=("Email already registered", "taken"),
        negative_markers=("Password is required",),
    ),
    EmailPlatformRule(
        name="Iyoni",
        category="Health",
        url="https://iyoni.app",
        check_url_template="https://api.iyoni.app/v1/user/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="MeetYou",
        category="Health",
        url="https://meetyou.me",
        check_url_template="https://api.meetyou.me/v1/user/check",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=('"exists":true',),
        negative_markers=('"exists":false',),
    ),
    EmailPlatformRule(
        name="MyPeriodTracker",
        category="Health",
        url="https://period-tracker.com",
        check_url_template="https://data.period-tracker.com/databackup/data.php",
        method="POST",
        data_payload={"action": "check_user", "email": "{email}"},
        positive_markers=('"status":"exist"', "exist"),
        negative_markers=('"status":"not_exist"', "not_exist"),
    ),
    EmailPlatformRule(
        name="Premom",
        category="Health",
        url="https://premom.com",
        check_url_template="https://api.premom.com/user/user/sign/up",
        method="POST",
        json_payload={"email": "{email}"},
        positive_markers=("Account already exists", "already taken"),
        negative_markers=("Password is required",),
    ),
    EmailPlatformRule(
        name="Bunny.net",
        category="Cloud",
        url="https://bunny.net",
        check_url_template="https://api.bunny.net/auth/register",
        method="POST",
        json_payload={"Email": "{email}"},
        positive_markers=("Email is already taken", "already in use"),
        negative_markers=("Password is required",),
    ),
    EmailPlatformRule(
        name="NeoCities",
        category="Cloud",
        url="https://neocities.org",
        check_url_template="https://neocities.org/site/new",
        method="POST",
        data_payload={"email": "{email}"},
        positive_markers=("Email is already taken",),
        negative_markers=("Password can't be blank",),
    ),
]
